# Generated by Django 4.2.6 on 2023-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fields", models.CharField(max_length=100)),
                ("Degree", models.CharField(max_length=100)),
                ("Skills", models.CharField(max_length=100)),
                ("Objectives", models.CharField(max_length=100)),
                ("Job", models.CharField(max_length=100)),
                ("PersonalityDescription", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fields", models.CharField(max_length=100)),
                (
                    "Degree",
                    models.CharField(
                        choices=[
                            ("BAC", "Bac"),
                            ("BTS", "BTS"),
                            ("DUT", "DUT"),
                            ("LIC", "Licence"),
                            ("MAS", "Master"),
                            ("DOC", "Doctorat"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Skills", models.CharField(max_length=100)),
                ("Objectives", models.CharField(max_length=100)),
                ("Job", models.CharField(max_length=100)),
                (
                    "PersonalityDescription",
                    models.CharField(blank=True, max_length=100),
                ),
            ],
        ),
    ]
