# Generated by Django 5.0.1 on 2024-01-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fields', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Objectives', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('PersonalityDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fields', models.CharField(max_length=100)),
                ('Degree', models.CharField(choices=[('BAC', 'Baccalauréat'), ('BTS', 'BTS'), ('DUT', 'DUT'), ('LIC', 'Bachelor/Licence'), ('MAS', 'Master'), ('DOC', 'PHD/Doctorat')], max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Objectives', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('PersonalityDescription', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('invitation', 'Invitation'), ('join_request', 'Join Request'), ('room_launched', 'Room launched'), ('mentor_promotion', 'Mentor Promotion')], default='invitation', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
