# Generated by Django 4.2.6 on 2023-12-14 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mentoring_app", "0002_alter_mentor_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="Degree",
            field=models.CharField(
                choices=[
                    ("BAC", "Baccalauréat"),
                    ("BTS", "BTS"),
                    ("DUT", "DUT"),
                    ("LIC", "Bachelor/Licence"),
                    ("MAS", "Master"),
                    ("DOC", "PHD/Doctorat"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
