# Generated by Django 4.2.9 on 2024-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('join_request', 'Join Request'), ('room_launched', 'Room launched'), ('mentor_promotion', 'Mentor Promotion'), ('renewal_reminder', 'Renewal Reminder')], default='invitation', max_length=20),
        ),
    ]
