# Generated by Django 4.2.6 on 2024-01-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0002_profile_is_mentor"),
        ("mentoring_app", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_mentor.profile",
            ),
        ),
    ]
