# Generated by Django 4.2.6 on 2023-12-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workgroup", "0003_workgroup_creator"),
        ("mentoring_app", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="workgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workgroup.workgroup",
            ),
        ),
    ]
