# Generated by Django 4.2.6 on 2023-12-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentoring_app", "0005_notification_workgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitation"),
                    ("join_request", "Join Request"),
                ],
                default="invitation",
                max_length=20,
            ),
        ),
    ]
