# Generated by Django 4.2.9 on 2024-01-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0007_coachingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='coaching_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
