# Generated by Django 4.2.6 on 2024-01-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentoring_app", "0007_mentor_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentor",
            name="user",
        ),
    ]
