# Generated by Django 4.2.6 on 2024-01-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0002_profile_is_mentor"),
        ("mentoring_app", "0008_remove_mentor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_mentor.profile",
            ),
            preserve_default=False,
        ),
    ]
