# Generated by Django 4.2.9 on 2024-01-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0008_notification_coaching_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='user',
            new_name='mentor',
        ),
    ]
