# Generated by Django 4.2.6 on 2024-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentoring_app", "0009_alter_mentor_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitation"),
                    ("join_request", "Join Request"),
                    ("room_launched", "Room launched"),
                    ("mentor_promotion", "Mentor Promotion"),
                ],
                default="invitation",
                max_length=20,
            ),
        ),
    ]
