# Generated by Django 4.2.6 on 2023-12-18 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workgroup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="members",
            field=models.ManyToManyField(
                related_name="invited_to_workgroups",
                through="workgroup.WorkGroupMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workgroupmember",
            unique_together={("workgroup", "user")},
        ),
    ]
