# Generated by Django 4.2.6 on 2023-12-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workgroup", "0002_workgroup_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_workgroups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
