# Generated by Django 4.2.6 on 2023-12-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0006_message"),
        ("workgroup", "0006_messageaudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="assistants",
            field=models.ManyToManyField(
                blank=True, related_name="workgroups", to="smart_mentor.openaiassistant"
            ),
        ),
    ]
