# Generated by Django 4.2.6 on 2023-12-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroup", "0007_workgroup_assistants"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="with_assistant",
            field=models.BooleanField(default=False),
        ),
    ]
