"""
Django settings for SocialNetwork project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    'https://jokk.net',
    'https://www.jokk.net',
    # Ajoutez ici d'autres domaines de confiance si nécessaire
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-sx*x4m+=8_5dlui2=1l47+a+9t!lr2tp9$7(#k@rnteg8t&o4j"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['134.209.196.111','jokk.net','www.jokk.net']
STRIPE_SECRET_KEY_TEST = "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"
PRODUCT_PRICE = "price_1OVkV9AdLeMTD97QWtMtNKpT"
MONTHLY_SUBSCRIPTION_PRICE = "price_1OXMQZAdLeMTD97Q5pGRGWyo"
WEEKLY_SUBSCRIPTION_PRICE = "price_1OXMRDAdLeMTD97QiLTnEYJV"
REDIRECT_DOMAIN = '134.209.196.111'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'jokkteam@gmail.com'
EMAIL_HOST_PASSWORD = 'gmez nymt nrwd wuzk'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'send-renewal-notifications-daily': {
        'task': 'user_payment.views.send_renewal_notifications',
        'schedule': crontab(hour=0, minute=0),  # Planifier pour s'exécuter tous les jours à minuit
    },
}
CELERY_BROKER_URL = 'redis://localhost:6379/0'
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'channels',
    'crispy_forms',
    "workgroup",
    "smart_mentor",
    "mentoring_app",
    'crispy_bootstrap4',
    'user_payment',
    'django_countries',
    'django_celery_beat',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "SocialNetwork.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n"
            ],
        },
    },
]

WSGI_APPLICATION = "SocialNetwork.wsgi.application"
ASGI_APPLICATION = 'SocialNetwork.asgi.application'
allowed_origins=['*']
AUTH_USER_MODEL = 'smart_mentor.CustomUser'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'jokk',
        'USER': 'jokk',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '',
    }
}
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

APPEND_SLASH = False

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

# Liste des langues prises en charge
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
]
LOCALE_PATHS= (
    BASE_DIR / 'locale',
)
LANGUAGE_CODE = "en"

# Formats de date et de temps
DATE_FORMATS = {
    'en': '%m/%d/%Y',  # Format anglophone MM/DD/YYYY
    'fr': '%d/%m/%Y',  # Format francophone JJ/MM/AAAA
}

# Localisations et formats de date par langue
FORMAT_MODULE_PATH = [
    'smart_mentor.formats',
]

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = '/home/webapps/jokk/Jokk_App/static/'


#STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/webapps/jokk/Jokk_App/media/'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CRISPY_TEMPLATE_PACK = 'bootstrap4'
