# Generated by Django 4.2.7 on 2023-12-06 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="avatars/")),
                ("phone", models.CharField(max_length=20)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("gender", models.CharField(max_length=10)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("skills", models.TextField(blank=True)),
                ("availability", models.CharField(blank=True, max_length=100)),
                ("social_media_links", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
