# Generated by Django 4.2.7 on 2023-12-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="availability",
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_media_links",
            field=models.URLField(blank=True),
        ),
    ]
