# Generated by Django 5.0.1 on 2024-01-14 15:11

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
