# Generated by Django 4.2.6 on 2024-01-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_mentor",
            field=models.BooleanField(default=False),
        ),
    ]
