# Generated by Django 4.2.9 on 2024-01-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mentor', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentor_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
