# Generated by Django 4.2.6 on 2024-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0003_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
