# Generated by Django 4.2.7 on 2023-12-13 07:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0004_openaiassistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
