# Generated by Django 4.2.6 on 2024-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0004_profile_first_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/pp.svg", upload_to="avatars/"
            ),
        ),
    ]
