# Generated by Django 4.2.6 on 2023-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_mentor", "0006_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="static/images/pp.svg", upload_to="avatars/"
            ),
        ),
    ]
