# Generated by Django 5.0.1 on 2024-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='failed_payment_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
