# Generated by Django 4.2.6 on 2024-01-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
