# Generated by Django 4.2.6 on 2024-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_payment", "0002_appuser_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userpayment",
            name="stripe_subscription_payment",
            field=models.BooleanField(default=False),
        ),
    ]
