# Generated by Django 4.2.9 on 2024-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment', '0002_appuser_failed_payment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
