# Generated by Django 4.2.9 on 2024-01-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment', '0003_appuser_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='has_been_premium',
            field=models.BooleanField(default=False),
        ),
    ]
